# Generated by Django 5.2.12 on 2026-03-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('course', models.CharField(blank=True, null=True)),
                ('phone_number', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField()),
                ('author', models.CharField()),
            ],
        ),
    ]
