# Generated by Django 5.2.12 on 2026-03-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_course_contact_subject_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.IntegerField(default=0),
        ),
    ]
